// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://umlkfipepaztbdayrokw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVtbGtmaXBlcGF6dGJkYXlyb2t3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE5OTExNTcsImV4cCI6MjA1NzU2NzE1N30.1PXmtyMeWvDj3HKhL5YFiY25aUil_vThecHOmUNuhaA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);